import { Metadata } from "next";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { courseService } from "@/server/services/course.service";
import Link from "next/link";
import { CommunityFeedClient } from "@/components/community-feed-client";
import { format } from "date-fns";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = {
  title: "Community | PathWeaver AI",
  description: "Discover and learn from community-created AI courses.",
};

export default async function CommunityPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string; sort?: 'trending' | 'topRated' }>;
}) {
  const params = await searchParams;
  const session = await auth();
  if (!session?.user?.id) {
    redirect("/api/auth/signin");
  }

  const query = params.q || "";
  const sort = params.sort || "trending";

  const courses = await courseService.getCommunityCourses(sort, query);

  // Fetch Active/Upcoming Live Parties
  const parties = await prisma.liveParty.findMany({
    where: { status: { in: ["LIVE", "SCHEDULED"] } },
    include: {
      host: { select: { id: true, name: true, image: true } },
      course: { select: { title: true } },
    },
    orderBy: [{ status: "asc" }, { scheduledAt: "asc" }],
    take: 6,
  });

  return (
    <div className="max-w-[1440px] mx-auto w-full space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h1 className="font-display-sm text-display-sm text-text-primary mb-2">Community Courses</h1>
          <p className="font-body-base text-body-base text-text-secondary">
            Discover courses generated by other learners. Clone them instantly and start learning.
          </p>
        </div>
        
        <div className="flex gap-4">
          <Link href={`/community?sort=trending${query ? `&q=${query}` : ''}`}>
            <button className={`px-4 py-2 rounded-lg font-label-mono text-sm uppercase tracking-wider transition-colors ${sort === 'trending' ? 'bg-primary text-white shadow-glow-primary' : 'bg-surface-2 text-text-muted hover:text-text-primary'}`}>
              Trending
            </button>
          </Link>
          <Link href={`/community?sort=topRated${query ? `&q=${query}` : ''}`}>
            <button className={`px-4 py-2 rounded-lg font-label-mono text-sm uppercase tracking-wider transition-colors ${sort === 'topRated' ? 'bg-primary text-white shadow-glow-primary' : 'bg-surface-2 text-text-muted hover:text-text-primary'}`}>
              Top Rated
            </button>
          </Link>
        </div>
      </div>

      {parties.length > 0 && (
        <section className="mb-sp-8">
          <div className="flex items-center justify-between mb-sp-4">
            <h2 className="font-headline-md text-headline-md text-text-primary">Live & Upcoming Parties</h2>
            <Link href="/live-parties" className="text-primary hover:text-primary-600 font-medium text-sm">
              View all
            </Link>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-sp-4">
            {parties.map((party: any) => (
              <Link key={party.id} href={`/live-parties`} className="block">
                <div className="bg-surface-glass border border-white/10 rounded-xl p-sp-4 hover:border-primary/50 transition-colors">
                  <div className="flex justify-between items-start mb-2">
                    <span className={`px-2 py-1 text-xs font-bold rounded uppercase ${party.status === 'LIVE' ? 'bg-error/20 text-error' : 'bg-surface-variant text-text-secondary'}`}>
                      {party.status === 'LIVE' ? 'Live Now' : format(new Date(party.scheduledAt!), "MMM d, h:mm a")}
                    </span>
                  </div>
                  <h3 className="font-medium text-text-primary mb-1 truncate">{party.title}</h3>
                  <p className="text-sm text-text-secondary truncate">Course: {party.course.title}</p>
                  <div className="mt-4 flex items-center gap-2">
                     <div className="w-6 h-6 rounded-full bg-surface-variant overflow-hidden">
                       {party.host.image ? <img src={party.host.image} /> : <span className="material-symbols-outlined text-[16px] m-1">person</span>}
                     </div>
                     <span className="text-xs text-text-muted">Host: {party.host.name}</span>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </section>
      )}

      <h2 className="font-headline-md text-headline-md text-text-primary mb-sp-4">Trending Courses</h2>
      {/* Grid */}
      <CommunityFeedClient initialCourses={courses} />
    </div>
  );
}
