import { Metadata } from "next";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import { courseService } from "@/server/services/course.service";
import { progressService } from "@/server/services/progress.service";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Circle, PlayCircle } from "lucide-react";
import { ReplanScheduleModal } from "@/components/ReplanScheduleModal";
import { DeleteCourseButton } from "@/components/DeleteCourseButton";
import { PublishCourseButton } from "@/components/PublishCourseButton";
import { StartWatchPartyButton } from "@/components/StartWatchPartyButton";
import { TogglePrivacyButton } from "@/components/TogglePrivacyButton";

type Props = {
  params: Promise<{ id: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const session = await auth();
  if (!session?.user?.id) {
    return { title: "Course | PathWeaver AI" };
  }

  const course = await prisma.course.findUnique({
    where: { id: id, userId: session.user.id },
  });

  if (!course) {
    return {
      title: "Course Not Found | PathWeaver AI",
    };
  }

  return {
    title: `${course.title} | PathWeaver AI`,
    description: course.description || "A personalized learning course generated by PathWeaver AI.",
  };
}

export default async function CourseOverviewPage({ params }: Props) {
  const { id } = await params;
  const session = await auth();
  if (!session?.user?.id) {
    redirect("/api/auth/signin");
  }

  const course = await courseService.getCourseWithTopics(id, session.user.id);
  const completedTopicIds = await progressService.getCompletedTopicIds(session.user.id);
  const topicMasteries = await progressService.getTopicMasteries(session.user.id, id);

  if (!course) {
    redirect("/dashboard");
  }

  // Calculate progress
  let totalLessons = 0;
  let completedLessons = 0;
  let firstIncompleteLessonId: string | null = null;
  let firstIncompleteModuleId: string | null = null;

  course.modules.forEach((module) => {
    module.topics.forEach((topic) => {
      totalLessons++;
      // Progress calculation implemented using LearningEvents
      const isCompleted = completedTopicIds.has(topic.id); 
      if (isCompleted) {
        completedLessons++;
      } else if (!firstIncompleteLessonId) {
        firstIncompleteLessonId = topic.id;
        firstIncompleteModuleId = module.id;
      }
    });
  });

  const progressPercentage =
    totalLessons === 0 ? 0 : Math.round((completedLessons / totalLessons) * 100);

  // Calculate Average Mastery
  const masteryScores = Object.values(topicMasteries);
  const averageMastery = masteryScores.length > 0 
    ? Math.round((masteryScores.reduce((a, b) => a + b, 0) / masteryScores.length) * 100) 
    : 0;

  // Default to first accordion item if all completed, else open the module with the first incomplete lesson
  const defaultValue = firstIncompleteModuleId || course.modules[0]?.id;

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
        <div>
          <Link
            href="/dashboard"
            className="inline-flex items-center text-sm font-label-mono text-text-secondary hover:text-primary mb-4 transition-colors"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Dashboard
          </Link>
          <h1 className="text-3xl font-bold tracking-tight text-text-primary">
            {course.title}
          </h1>
          <p className="text-text-secondary mt-2 text-lg">{course.description}</p>
        </div>
        {course.status === "ACTIVE" && (
          <div className="flex shrink-0">
            <PublishCourseButton courseId={course.id} isPublished={course.isPublished} />
          </div>
        )}
      </div>

      {/* Progress Card */}
      <div className="glass-panel p-6 flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex-1 space-y-2">
          <div className="flex items-center justify-between text-sm font-medium">
            <span className="text-text-primary">Course Progress</span>
            <span className="text-primary">{progressPercentage}%</span>
          </div>
          <Progress value={progressPercentage} className="h-2" />
          <div className="flex justify-between items-center text-sm text-text-secondary mt-2">
            <p>
              {completedLessons} of {totalLessons} lessons completed
            </p>
            {masteryScores.length > 0 && (
              <p className="flex items-center gap-1 font-medium text-emerald-400 bg-emerald-900/30 px-2 py-0.5 rounded-full border border-emerald-500/20">
                <span className="material-symbols-outlined text-[14px]">school</span>
                {averageMastery}% Avg Mastery
              </p>
            )}
          </div>
        </div>
        <div className="flex flex-wrap items-center gap-3 w-full sm:w-auto">
          <TogglePrivacyButton courseId={course.id} initialIsPublic={course.isPublic} />
          <PublishCourseButton courseId={course.id} isPublished={course.isPublished} />
          <StartWatchPartyButton courseId={course.id} />
          <DeleteCourseButton courseId={course.id} />
          <ReplanScheduleModal courseId={course.id} />
          {firstIncompleteLessonId ? (
            <Link
              href={`/courses/${course.id}/lesson/${firstIncompleteLessonId}`}
            >
              <Button size="lg" className="w-full md:w-auto font-medium bg-primary-gradient border border-white/10 hover:shadow-glow-primary transition-all hover:scale-105 active:scale-95">
                <PlayCircle className="w-5 h-5 mr-2" />
                {completedLessons === 0 ? "Start Course" : "Continue Learning"}
              </Button>
            </Link>
          ) : (
            <Button size="lg" disabled className="w-full md:w-auto font-medium">
              <CheckCircle2 className="w-5 h-5 mr-2" />
              Course Completed
            </Button>
          )}
        </div>
      </div>

      {/* Curriculum Accordion */}
      <div>
        <h2 className="text-xl font-bold text-text-primary mb-4">Curriculum</h2>
        <Accordion
          defaultValue={defaultValue ? [defaultValue] : []}
          className="space-y-4"
        >
          {course.modules.map((module, index) => (
            <AccordionItem
              key={module.id}
              value={module.id}
              className="glass-panel px-4 overflow-hidden"
            >
              <AccordionTrigger className="hover:no-underline py-4">
                <div className="flex flex-col text-left">
                  <span className="text-sm font-semibold text-primary uppercase tracking-wider mb-1">
                    Module {index + 1}
                  </span>
                  <span className="text-lg font-medium text-text-primary">
                    {module.title}
                  </span>
                </div>
              </AccordionTrigger>
              <AccordionContent className="pt-2 pb-4">
                <div className="space-y-2">
                  {module.topics.map((topic) => {
                    const isCompleted = completedTopicIds.has(topic.id);
                    return (
                    <Link
                      key={topic.id}
                      href={`/courses/${course.id}/lesson/${topic.id}`}
                      className={`group flex items-center justify-between p-3 rounded-md transition-colors border border-transparent ${
                        isCompleted
                          ? "bg-surface-2/30 border-white/5"
                          : "hover:bg-primary/5 hover:border-primary/20"
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        {isCompleted ? (
                          <CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" />
                        ) : (
                          <Circle className="w-5 h-5 text-text-muted group-hover:text-primary flex-shrink-0 transition-colors" />
                        )}
                        <span
                          className={`font-medium transition-colors ${
                            isCompleted
                              ? "text-text-muted line-through decoration-text-muted/50"
                              : "text-text-primary group-hover:text-primary"
                          }`}
                        >
                          {topic.title}
                        </span>
                      </div>
                      <div className="flex items-center gap-4">
                        {/* Optional Mastery Badge */}
                        {topicMasteries[topic.id] !== undefined && (
                          <div className="text-xs font-semibold text-emerald-400 bg-emerald-900/30 px-2 py-1 rounded-full border border-emerald-500/20 whitespace-nowrap">
                            {Math.round(topicMasteries[topic.id] * 100)}% Mastery
                          </div>
                        )}
                        <span className="text-sm font-label-mono text-text-secondary whitespace-nowrap">
                          {topic.estimatedMins} mins
                        </span>
                      </div>
                    </Link>
                    )
                  })}
                </div>
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </div>
  );
}
