"use client";

import ReactMarkdown from "react-markdown";
import { BookOpen, Loader2, Edit3, Save, X } from "lucide-react";
import { useTransition, useState } from "react";
import { useRouter } from "next/navigation";
import { generateMissingArticleAction, updateArticleAction } from "@/server/actions/course";
import { WysiwygEditor } from "@/components/ui/wysiwyg-editor";

type LessonArticleTabProps = {
  topicId: string;
  content?: string | null;
  onSeekTo?: (seconds: number) => void;
};

export function LessonArticleTab({ topicId, content, onSeekTo }: LessonArticleTabProps) {
  const [isPending, startTransition] = useTransition();
  const router = useRouter();

  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState(content || "");
  const [isSaving, startSaving] = useTransition();

  const handleGenerate = () => {
    startTransition(async () => {
      await generateMissingArticleAction(topicId);
      router.refresh();
    });
  };

  const handleSave = () => {
    startSaving(async () => {
      const result = await updateArticleAction(topicId, editedContent);
      if (result.success) {
        setIsEditing(false);
        router.refresh();
      } else {
        alert(result.error || "Failed to save article");
      }
    });
  };

  if (!content) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center text-text-muted p-sp-6 border-2 border-dashed border-white/10 m-sp-4 rounded-xl">
        <BookOpen className="w-12 h-12 mb-4 opacity-50" />
        <p className="font-body-base">No article available for this lesson yet.</p>
        <p className="text-sm opacity-70 mt-2 text-center max-w-sm mb-6">
          Deep Dive articles are generated by AI. This one might still be processing.
        </p>
        <button
          onClick={handleGenerate}
          disabled={isPending}
          className="px-4 py-2 bg-primary/20 hover:bg-primary/30 text-primary border border-primary/30 rounded-lg font-label-md transition-colors flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isPending ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              Generating...
            </>
          ) : (
            "Generate Deep Dive"
          )}
        </button>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col overflow-hidden w-full">
      {/* Tab Header Controls */}
      <div className="flex justify-end p-4 border-b border-white/10 shrink-0">
        {isEditing ? (
          <div className="flex items-center gap-2">
            <button
              onClick={() => {
                setEditedContent(content); // Revert
                setIsEditing(false);
              }}
              disabled={isSaving}
              className="px-3 py-1.5 flex items-center gap-2 text-text-secondary hover:text-text-primary bg-surface-2 hover:bg-surface-3 border border-white/10 rounded-md font-label-sm transition-colors disabled:opacity-50"
            >
              <X className="w-4 h-4" /> Cancel
            </button>
            <button
              onClick={handleSave}
              disabled={isSaving}
              className="px-3 py-1.5 flex items-center gap-2 text-white bg-primary hover:bg-primary/90 border border-primary/30 rounded-md font-label-sm shadow-glow-primary transition-all disabled:opacity-50"
            >
              {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />} 
              Save Changes
            </button>
          </div>
        ) : (
          <button
            onClick={() => {
              setEditedContent(content);
              setIsEditing(true);
            }}
            className="px-3 py-1.5 flex items-center gap-2 text-primary hover:text-primary-container bg-primary/10 hover:bg-primary/20 border border-primary/30 rounded-md font-label-sm transition-colors"
          >
            <Edit3 className="w-4 h-4" /> Edit Article
          </button>
        )}
      </div>

      <div className="flex-1 overflow-y-auto overflow-x-hidden hide-scrollbar p-sp-6 w-full">
        {isEditing ? (
          <WysiwygEditor 
            initialContent={editedContent}
            onChange={(newMarkdown) => setEditedContent(newMarkdown)}
          />
        ) : (
          <article className="prose prose-invert prose-primary max-w-none w-full break-words
            prose-headings:font-display-md prose-headings:font-bold prose-headings:text-text-primary
            prose-h1:text-3xl prose-h2:text-2xl prose-h3:text-xl
            prose-p:font-body-base prose-p:text-text-secondary prose-p:leading-relaxed
            prose-strong:text-primary-container
            prose-ul:list-disc prose-ul:ml-6 prose-ol:list-decimal prose-ol:ml-6
            prose-li:text-text-secondary prose-li:mb-1
            prose-code:bg-surface-2 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-primary-container prose-code:before:content-none prose-code:after:content-none
            prose-pre:bg-surface-2 prose-pre:border prose-pre:border-white/10 prose-pre:rounded-lg prose-pre:overflow-x-auto prose-pre:max-w-full">
            <ReactMarkdown
              components={{
                a: ({ node, href, children, ...props }) => {
                  if (href?.startsWith("#t=")) {
                    const seconds = parseInt(href.replace("#t=", ""), 10);
                    return (
                      <button
                        onClick={() => onSeekTo && onSeekTo(seconds)}
                        className="inline-flex items-center gap-1 text-primary hover:text-primary-container hover:underline px-1.5 py-0.5 rounded-md bg-primary/10 transition-colors font-mono text-sm align-baseline"
                        title={`Jump to ${Math.floor(seconds / 60)}:${(seconds % 60).toString().padStart(2, '0')} in video`}
                      >
                        <span className="material-symbols-outlined text-[14px]">play_circle</span>
                        {children}
                      </button>
                    );
                  }
                  return <a href={href} {...props} className="text-primary hover:underline">{children}</a>;
                }
              }}
            >
              {content}
            </ReactMarkdown>
          </article>
        )}
      </div>
    </div>
  );
}
